services:
  elixir:
    build:
      context: .
      args:
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    container_name: northwind_elixir_traders_app
    user: "${APP_UID}:${APP_GID}"
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    command: tail -f /dev/null
